# PinAPLPy: Platform-independent Analysis of Pooled Screens using Python
# P. Spahn et al., UC San Diego 

# ***********************************************************************
# CONFIGURATION FILE
# ***********************************************************************

# PROJECT PARAMETERS
ScreenType: 'enrichment'              # type of screen ['enrichment'/'depletion']

# LIBRARY PARAMETERS
LibFilename: 'vf_grna.csv'        # filename of library spreadsheet
seq_5_end: 'TCTTGTGGAAAGGACGAAACACCN'       # 5'-sequence adapter
NonTargetPrefix: 'NT_'             # prefix for non-targeting sgRNAs in library
NumGuidesPerGene: 5                     # number of sgRNAs per gene 
                                       
# ANALYSIS OPTIONS
GeneMetric: 'AvgLogFC'                   # metric for gene ranking ['SigmaFC'/'AvgLogFC'/'aRRA'/'STARS']
padj: 'fdr_bh'                          # method for p-value adjustment ['fdr_bh'/'sidak'/'bonferroni']
alpha_s: 0.01                            # significance threshold (sgRNAs enrichment/depletion)
alpha_g: 0.0015                            # significance threshold (gene ranking)
Normalization: 'total'                    # normalization of read counts ['cpm'/'size'/'total']
ClusterBy: 'variance'                   # clustering criterion ['variance'/'counts']
RoundCount: False                       # round counts after normalization [True/False]
repl_avg: 'median'                      # average counts between replicates ['mean'/'median']
sgRNALength: 20                         # sgRNA length [bp]
AS_min: 0                              # alignment matching threshold 
Theta: 2                                # alignment ambiguity threshold
Np: 10000                               # number of permutations for gene ranking p-values
w_SigmaFC: [0,1,2,3,4,5,6]              # weighing function for SigmaFC score
thr_STARS: 10                           # threshold percentage for STARS analysis
TopN: 25                                # number of top sgRNAs to take into account for clustering
ShowNonTargets: True                    # show non-targeting controls in scatterplots [True/False]
scatter_annotate: False                 # annotate highlighted sgRNAs in scatterplots [True/False]
IncludeDensityPlots: False              # include sgRNA density plots [True/False]
AutoHighlight: False                     # automatically highlight the top 10 ranked genes [True/False]

# TECHNICAL PARAMETERS (changes not required/recommended)
Cutoff: 0                       # read count threshold
CutErrorTol: 0.1                # cutadapt error tolerance
L_bw: 11                        # Bowtie2 -L parameter (seed length)
N_bw: 1                         # Bowtie2 -N parameter (seed mismatch)
i_bw: 'S,1,0.75'                # Bowtie2 -i parameter (interval function)
delta: 1                        # count shift to avoid zero counts in logFC
p_overdisp: 0.05                # significance threshold for overdispersion test
dotsize: 10                     # size of dots in scatterplot
TransparencyLevel: 0.05         # transparency (alpha) in scatterplots
logbase: 10                     # base for log transformation in scatterplots
AlnOutput: 'Delete'             # keep raw alignment output? ['Keep'/'Compress'/'Delete']
keepCutReads: False             # keep files containing trimmed reads? [True/False]
dpi: 300                        # resolution of PNG plots
svg: True                       # save figures as vector graphics?  [True/False]
HitListFormat: 'xlsx'                # format of results spreadsheets ['txt'/'xlsx']
PrintHighlights: True              # print highlighted sgRNA info in console [True/False]

# HARD-CODED PARAMETERS (not available on website)
FCmin_SigmaFC: 0                        # minimal FC required for SigmaFC score (not compatible with depletion screen)
IncludeGeneRankCombination: False       # Fishers statistic for p-value combination
width_p: 800                            # width of heatmap image (pixels)
height_p: 800                           # height of heatmap image (pixels)
fontsize_p: 14                          # fontsize in heatmap image
marginsize: 10                          # size of margin in heatmap image

# DIRECTORIES
WorkingDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/'
DataDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Data/'
TempDataDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/TempData/'
LibDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Library/'
IndexDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Library/Bowtie2_Index/'
ScriptsDir: '/home/laeb/PycharmProjects/PinAPL-Py/Scripts/'
AlignDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Alignments/'
AnalysisDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/'
TrimLogDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/01_Alignment_Results/Read_Trimming/'
sgRNARanksDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/sgRNA_Ranking/'
GeneDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/03_GeneRanking_Results/Gene_Ranking/'
ControlDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/ControlSample_Analysis/'
HeatDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/Heatmap/'
AlnQCDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/01_Alignment_Results/Alignment_Statistics/'
sgRNAReadCountDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/01_Alignment_Results/ReadCounts_per_sgRNA/'
GeneReadCountDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/01_Alignment_Results/ReadCounts_per_Gene/'
CountQCDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/ReadCount_Distribution/'
ScatterDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/sgRNA_Scatterplots/'
DensityDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/sgRNA_Densities/'
GenePlotDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/03_GeneRanking_Results/GeneScore_Scatterplots/'
CorrelDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/Replicate_Correlation/'
HiLiteDir2: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/Replicate_Correlation/Highlighted_Genes/'
EffDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/03_GeneRanking_Results/sgRNA_Efficacy/'
DepthDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/01_Alignment_Results/Read_Depth/'
SeqQCDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/01_Alignment_Results/Sequence_Quality/'
pvalDir_sgRNA: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/p-value_Distribution/' 
pvalDir_genes: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/03_GeneRanking_Results/p-value_Distribution/' 
zScoreDir_sgRNA: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/sgRNA_z-Scores/'
VolcanoDir_sgRNA: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/02_sgRNA-Ranking_Results/sgRNA_VolcanoPlots/'
LogFileDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Analysis/00_LogFile/' 
bw2Dir: '/usr/bin/'
CutAdaptDir: '/usr/bin/'    
STARSDir: '/home/laeb/PycharmProjects/PinAPL-Py/workingdir/Scripts/STARS_mod/'

# SCRIPT FILENAMES
SanityScript: 'CheckCharacters'
IndexScript: 'BuildLibraryIndex'
LoaderScript: 'LoadDataSheet'
ReadDepthScript: 'PlotNumReads'
SeqQCScript: 'CheckSequenceQuality'
TrimScript: 'TrimReads'
AlignScript: 'AlignReads'
ClassifyScript: 'GetReadCounts'
CutoffScript: 'ApplyCutoff'
CleanUpScript: 'RemoveTempOutput'
NormalizeScript: 'NormalizeReadCounts'
AverageCountsScript: 'AverageCounts'
StatsScript: 'AnalyzeReadCounts'
ControlScript: 'AnalyzeControl'
sgRNARankScript: 'RanksgRNAs'
zFCScript: 'PlotFCz'
vFCScript: 'PlotFCvolcano'
GeneRankScript: 'RankGenes'
GenePlotScript: 'PlotGeneScores'
CombineScript: 'CombineGeneRanks'
ScatterScript: 'PlotCounts'
DensityScript: 'PlotDensity'
ReplicateScript: 'PlotReplicates'
ClusterScript: 'PlotHeatmap'
ExtractTop10Script: 'ExtractTop10Genes'
